<article class="post">
        <h2><a href="[field:arcurl/]" title="[field:title/]">[field:title/]</a></h2>
        <p class="post-meta">[field:pubdate function="MyDate('Y-m-d',@me)"/] <span>|</span> 点击：[field:click/]</p>
        <div class="img medium"> <a href="[field:arcurl/]" title="[field:title/]"><img src="[field:picname/]" alt="[field:title/]" style="width:300px;" /></a> </div>
        <p>[field:description function="cn_substr(@me,400)"/]...</p>
        <p class="more"><a href="[field:arcurl/]">查看详细</a></p>
      </article>