<?php
$z[0]=Array("arcurl","",45,60);
$z[1]=Array("title","",69,83);
$z[2]=Array("title","",85,99);
$z[3]=Array("pubdate","",139,186);
$z[3][4]['function']="MyDate('Y-m-d',@me)";
$z[4]=Array("click","",211,225);
$z[5]=Array("arcurl","",273,288);
$z[6]=Array("title","",297,311);
$z[7]=Array("picname","",323,339);
$z[8]=Array("title","",346,360);
$z[9]=Array("description","",409,459);
$z[9][4]['function']="cn_substr(@me,400)";
$z[10]=Array("arcurl","",501,516);

?>