<?php
$z[0]=Array("field","",66,85);
$z[0][4]['name']="title";
$z[1]=Array("global","",86,112);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",153,175);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",215,266);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("global","",825,852);
$z[4][4]['name']="cfg_basehost";
$z[5]=Array("include","",1074,1109);
$z[5][4]['filename']="head.htm";
$z[6]=Array("field","",1154,1183);
$z[6][4]['name']="position";
$z[7]=Array("field","\r\n          <li style=\"float:none; display:block;\"><a href=\"[field:imgsrc/]\"><span class=\"zoom_in\"></span><img class=\"design-logo\" src=\"[field:imgsrc/]\" width=\"300\" height=\"300\" /></a></li>\r\n          ",1377,1640);
$z[7][4]['name']="imgurls";
$z[7][4]['alt']="图片输出区";
$z[8]=Array("productimagelist","\r\n          <li style=\"border:none;\"><a href=\"[field:imgsrc/]\"><img src=\"[field:imgsrc/]\" width=\"65\" height=\"65\" /></a></li>\r\n          ",1780,1963);
$z[9]=Array("field","",2218,2234);
$z[9][4]['name']="cc";
$z[10]=Array("field","",2329,2345);
$z[10][4]['name']="zl";
$z[11]=Array("field","",2446,2462);
$z[11][4]['name']="pl";
$z[12]=Array("field","",2563,2579);
$z[12][4]['name']="jl";
$z[13]=Array("field","",2811,2827);
$z[13][4]['name']="nr";
$z[14]=Array("field","",2955,2973);
$z[14][4]['name']="body";
$z[15]=Array("include","",3150,3187);
$z[15][4]['filename']="footer.htm";

?>