<?php
$z[0]=Array("arcurl","",66,81);
$z[1]=Array("picname","",128,144);
$z[2]=Array("arcurl","",242,257);
$z[3]=Array("arcurl","",377,392);
$z[4]=Array("title","",394,408);
$z[5]=Array("pubdate","",485,539);
$z[5][4]['function']="MyDate('y年m月d日',@me)";
$z[6]=Array("typeurl","",623,639);
$z[7]=Array("typename","",641,658);
$z[8]=Array("click","",685,699);
$z[9]=Array("info","",726,739);
$z[10]=Array("arcurl","",751,766);

?>