<?php
$z[0]=Array("global","",113,138);
$z[0][4]['name']="cfg_cmsurl";
$z[1]=Array("global","",546,571);
$z[1][4]['name']="cfg_cmsurl";
$z[2]=Array("channel","\r\n			<li class=\"menu-item menu-item-type-taxonomy menu-item-object-category\"><a title=\"[field:typename/]\" href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n            ",594,839);
$z[2][4]['row']="4";
$z[2][4]['type']="top";

?>