<?php
$z[0]=Array("global","",214,240);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",284,314);
$z[1][4]['name']="cfg_description";
$z[2]=Array("global","",351,378);
$z[2][4]['name']="cfg_keywords";
$z[3]=Array("include","",917,952);
$z[3][4]['filename']="head.htm";
$z[4]=Array("arclist","\r\n\r\n    <section class=\"list\">\r\n    <span class=\"titleimg\">\r\n    <a href=\"[field:arcurl/]\">\r\n        <img width=\"270\" height=\"165\" src=\"[field:picname/]\" class=\"attachment-thumbnail wp-post-image\" /></a>\r\n         </span>\r\n        \r\n        <a href=\"[field:arcurl/]\" class=\"up\" ></a>\r\n		      <div class=\"mecc\">\r\n            <h2 class=\"mecctitle\">\r\n            \r\n             <a href=\"[field:arcurl/]\">[field:title/]</a> </h2>\r\n            <address class=\"meccaddress\">\r\n                <time>[field:pubdate function=\"MyDate('y年m月d日',@me)\"/]</time>\r\n                <img src=\"/skin/Picture/n.png\">\r\n                <a href='/[field:typeurl/]'>[field:typename/]</a> -\r\n                阅[field:click/]</address>\r\n            <p>[field:info/]...<a href=\"[field:arcurl/]\">[查看全文]</a></p>\r\n        </div>\r\n        <div class=\"clear\"></div>\r\n\r\n    </section>\r\n  ",1323,2262);
$z[4][4]['row']="15";
$z[4][4]['titlelen']="80";
$z[4][4]['infolen']="200";
$z[5]=Array("include","",2371,2407);
$z[5][4]['filename']="right.htm";
$z[6]=Array("include","",2474,2511);
$z[6][4]['filename']="footer.htm";

?>