<?php
$z[0]=Array("field","",66,85);
$z[0][4]['name']="title";
$z[1]=Array("global","",86,112);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",153,182);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",222,280);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",755,790);
$z[4][4]['filename']="head.htm";
$z[5]=Array("field","",835,864);
$z[5][4]['name']="position";
$z[6]=Array("field","",912,933);
$z[6][4]['name']="content";
$z[7]=Array("channel","\r\n          <li><a href=\"[field:typeurl/]\">[field:typename/]</a></li>\r\n          ",1002,1251);
$z[7][4]['type']="son";
$z[7][4]['currentstyle']="<li class='current-menu-item'><a href='~typelink~' class='thisclass'>~typename~</a></li>";
$z[8]=Array("include","",1357,1394);
$z[8][4]['filename']="footer.htm";

?>