<?php
$z[0]=Array("field","",66,85);
$z[0][4]['name']="title";
$z[1]=Array("global","",86,112);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",153,182);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",222,280);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("global","",669,696);
$z[4][4]['name']="cfg_basehost";
$z[5]=Array("include","",912,947);
$z[5][4]['filename']="head.htm";
$z[6]=Array("field","",992,1021);
$z[6][4]['name']="position";
$z[7]=Array("list","\r\n      <article class=\"col3 danpin\">\r\n        <div class=\"img\"> <a href=\"[field:arcurl/]\" title=\"[field:title/]\"><img src=\"[field:picname/]\" alt=\"[field:title/]\" style=\"width:310px; height:206px;\" /></a> </div>\r\n        <h3><a href=\"[field:arcurl/]\" title=\"[field:title/]\">[field:title/]</a></h3>\r\n      </article>\r\n      ",1160,1520);
$z[7][4]['pagesize']="21";
$z[8]=Array("include","",3142,3179);
$z[8][4]['filename']="footer.htm";

?>