<?php
$z[0]=Array("tag","\r\n                    <li class=\"menu-item menu-item-type-custom menu-item-object-custom\"><a href=\"[field:link/]\">[field:tag /]</a></li>\r\n                        ",374,581);
$z[0][4]['sort']="month";
$z[0][4]['row']="15";
$z[1]=Array("arclist","\r\n      \r\n<li><a href=\"[field:arcurl/]\">[field:title/]</a></li>\r\n",820,968);
$z[1][4]['orderby']="pubdate";
$z[1][4]['flag']="c";
$z[1][4]['titlelen']="42";
$z[1][4]['row']="5";
$z[2]=Array("arclist","\r\n<li><a href=\"[field:arcurl/]\">[field:title/]</a></li>\r\n   ",1131,1259);
$z[2][4]['orderby']="click";
$z[2][4]['titlelen']="42";
$z[2][4]['row']="5";

?>